services:
  - type: web
    name: desk-mate-site
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_SECRET_KEY
        sync: false
      - key: SITE_PASSWORD
        sync: false
      - key: DEVICE_API_KEY
        sync: false
