#include "Cards.h"

// TODO: replace placeholder text with the real 10 messages.
// No bitmaps chosen yet -> bitmap = nullptr, bmpW/bmpH unused in that case.
// To add one later: convert an image with image2cpp (https://javl.github.io/image2cpp/),
// paste the generated byte array above this table, and reference it here.
const Card cards[] = {
  { "Card 1\n\nTODO: write\nyour message\nhere.",  nullptr, 0, 0 },
  { "Card 2\n\nTODO: write\nyour message\nhere.",  nullptr, 0, 0 },
  { "Card 3\n\nTODO: write\nyour message\nhere.",  nullptr, 0, 0 },
  { "Card 4\n\nTODO: write\nyour message\nhere.",  nullptr, 0, 0 },
  { "Card 5\n\nTODO: write\nyour message\nhere.",  nullptr, 0, 0 },
  { "Card 6\n\nTODO: write\nyour message\nhere.",  nullptr, 0, 0 },
  { "Card 7\n\nTODO: write\nyour message\nhere.",  nullptr, 0, 0 },
  { "Card 8\n\nTODO: write\nyour message\nhere.",  nullptr, 0, 0 },
  { "Card 9\n\nTODO: write\nyour message\nhere.",  nullptr, 0, 0 },
  { "Card 10\n\nTODO: write\nyour message\nhere.", nullptr, 0, 0 },
};

const uint8_t NUM_CARDS = sizeof(cards) / sizeof(cards[0]);

const Card& getCardContent(int index) {
  int wrapped = ((index % NUM_CARDS) + NUM_CARDS) % NUM_CARDS;
  return cards[wrapped];
}
